import type { SkillCategory, LabelLanguage } from "./cv";

export const SKILL_CATEGORY_LABELS = {
  id: {
    software: "Perangkat Lunak",
    tools: "Alat/Tools",
    hard_skill: "Hard Skill",
    soft_skill: "Soft Skill",
    other: "Lainnya",

    ms_office: "Microsoft Office",
    google_workspace: "Google Workspace",
    data_entry: "Entri Data",
    administration: "Administrasi",
    secretarial: "Kesekretariatan",
    document_management: "Manajemen Dokumen",
    archiving: "Kearsipan",
    scheduling: "Penjadwalan",
    virtual_assistant: "Asisten Virtual",

    communication: "Komunikasi",
    public_speaking: "Public Speaking",
    presentation: "Presentasi",
    negotiation: "Negosiasi",
    customer_service: "Layanan Pelanggan",
    sales: "Penjualan",
    business_development: "Pengembangan Bisnis",
    leadership: "Kepemimpinan",
    teamwork: "Kerja Tim",
    problem_solving: "Pemecahan Masalah",
    time_management: "Manajemen Waktu",
    critical_thinking: "Berpikir Kritis",
    training_facilitation: "Fasilitasi Pelatihan",
    coaching_mentoring: "Coaching & Mentoring",

    language: "Bahasa",
    translation: "Penerjemahan",
    interpretation: "Interpretasi",

    programming_language: "Bahasa Pemrograman",
    web_development: "Pengembangan Web",
    mobile_development: "Pengembangan Mobile",
    backend_development: "Backend Development",
    frontend_development: "Frontend Development",
    fullstack_development: "Fullstack Development",
    api_development: "Pengembangan API",
    system_design: "Desain Sistem",
    algorithms: "Algoritma",
    data_structures: "Struktur Data",
    version_control: "Kontrol Versi",
    code_review: "Code Review",
    refactoring: "Refactoring",

    framework_library: "Framework/Library",
    cms: "CMS",
    ecommerce_platform: "Platform E-commerce",

    data_analysis: "Analisis Data",
    data_science: "Data Science",
    machine_learning: "Machine Learning",
    deep_learning: "Deep Learning",
    nlp: "NLP (Pemrosesan Bahasa Alami)",
    computer_vision: "Computer Vision",
    data_engineering: "Data Engineering",
    etl_elt: "ETL/ELT",
    business_intelligence: "Business Intelligence",
    statistics: "Statistik",
    experimentation_ab_testing: "Eksperimen & A/B Testing",
    analytics: "Analitik",

    database_sql: "Database (SQL)",
    database_nosql: "Database (NoSQL)",
    data_warehouse: "Data Warehouse",
    data_lake: "Data Lake",

    devops: "DevOps",
    ci_cd: "CI/CD",
    containerization: "Kontainerisasi",
    orchestration: "Orkestrasi",
    cloud_computing: "Komputasi Cloud",
    linux: "Linux",
    networking: "Jaringan",
    site_reliability: "Site Reliability (SRE)",
    monitoring_observability: "Monitoring & Observability",
    infrastructure_as_code: "Infrastructure as Code (IaC)",

    cybersecurity: "Keamanan Siber",
    app_security: "Keamanan Aplikasi",
    network_security: "Keamanan Jaringan",
    iam_security: "IAM (Identity & Access Management)",
    vulnerability_management: "Manajemen Kerentanan",
    penetration_testing: "Uji Penetrasi (Pentest)",

    quality_assurance: "Quality Assurance (QA)",
    manual_testing: "Pengujian Manual",
    automation_testing: "Pengujian Otomatis",
    performance_testing: "Pengujian Performa",
    test_management: "Manajemen Pengujian",

    ui_ux_design: "Desain UI/UX",
    product_design: "Desain Produk",
    graphic_design: "Desain Grafis",
    branding: "Branding",
    illustration: "Ilustrasi",
    video_editing: "Editing Video",
    motion_graphics: "Motion Graphics",
    photography: "Fotografi",
    copywriting: "Copywriting",
    content_writing: "Penulisan Konten",
    content_strategy: "Strategi Konten",

    product_management: "Manajemen Produk",
    project_management: "Manajemen Proyek",
    program_management: "Manajemen Program",
    agile_scrum: "Agile/Scrum",
    business_analysis: "Analisis Bisnis",
    process_improvement: "Perbaikan Proses",
    operations: "Operasional",
    strategy_planning: "Perencanaan Strategi",
    okr_kpi: "OKR/KPI",

    digital_marketing: "Digital Marketing",
    social_media: "Media Sosial",
    seo: "SEO",
    sem_ppc: "SEM/PPC",
    email_marketing: "Email Marketing",
    performance_marketing: "Performance Marketing",
    brand_marketing: "Brand Marketing",
    market_research: "Riset Pasar",
    pr_communications: "PR & Komunikasi",
    community_management: "Manajemen Komunitas",

    finance: "Keuangan",
    accounting: "Akuntansi",
    bookkeeping: "Pembukuan",
    taxation: "Perpajakan",
    budgeting_forecasting: "Anggaran & Forecasting",
    financial_analysis: "Analisis Keuangan",
    audit_compliance: "Audit & Kepatuhan",

    human_resources: "SDM (HR)",
    recruitment: "Rekrutmen",
    people_operations: "People Operations",
    payroll: "Payroll",
    learning_development: "Learning & Development",

    legal: "Legal/Hukum",
    contract_management: "Manajemen Kontrak",
    compliance: "Kepatuhan",
    risk_management: "Manajemen Risiko",

    procurement: "Pengadaan (Procurement)",
    inventory_management: "Manajemen Inventori",
    supply_chain: "Supply Chain",
    logistics: "Logistik",
    warehouse_management: "Manajemen Gudang",
    shipping_fulfillment: "Pengiriman & Fulfillment",

    healthcare: "Kesehatan",
    education: "Pendidikan",
    hospitality: "Hospitality/Perhotelan",
    retail: "Ritel",
    manufacturing: "Manufaktur",
    construction: "Konstruksi",
  },

  en: {
    software: "Software",
    tools: "Tools",
    hard_skill: "Hard Skill",
    soft_skill: "Soft Skill",
    other: "Other",

    ms_office: "Microsoft Office",
    google_workspace: "Google Workspace",
    data_entry: "Data Entry",
    administration: "Administration",
    secretarial: "Secretarial",
    document_management: "Document Management",
    archiving: "Archiving",
    scheduling: "Scheduling",
    virtual_assistant: "Virtual Assistant",

    communication: "Communication",
    public_speaking: "Public Speaking",
    presentation: "Presentation",
    negotiation: "Negotiation",
    customer_service: "Customer Service",
    sales: "Sales",
    business_development: "Business Development",
    leadership: "Leadership",
    teamwork: "Teamwork",
    problem_solving: "Problem Solving",
    time_management: "Time Management",
    critical_thinking: "Critical Thinking",
    training_facilitation: "Training Facilitation",
    coaching_mentoring: "Coaching & Mentoring",

    language: "Language",
    translation: "Translation",
    interpretation: "Interpretation",

    programming_language: "Programming Language",
    web_development: "Web Development",
    mobile_development: "Mobile Development",
    backend_development: "Backend Development",
    frontend_development: "Frontend Development",
    fullstack_development: "Full-Stack Development",
    api_development: "API Development",
    system_design: "System Design",
    algorithms: "Algorithms",
    data_structures: "Data Structures",
    version_control: "Version Control",
    code_review: "Code Review",
    refactoring: "Refactoring",

    framework_library: "Framework/Library",
    cms: "CMS",
    ecommerce_platform: "E-commerce Platform",

    data_analysis: "Data Analysis",
    data_science: "Data Science",
    machine_learning: "Machine Learning",
    deep_learning: "Deep Learning",
    nlp: "NLP (Natural Language Processing)",
    computer_vision: "Computer Vision",
    data_engineering: "Data Engineering",
    etl_elt: "ETL/ELT",
    business_intelligence: "Business Intelligence",
    statistics: "Statistics",
    experimentation_ab_testing: "Experimentation & A/B Testing",
    analytics: "Analytics",

    database_sql: "Database (SQL)",
    database_nosql: "Database (NoSQL)",
    data_warehouse: "Data Warehouse",
    data_lake: "Data Lake",

    devops: "DevOps",
    ci_cd: "CI/CD",
    containerization: "Containerization",
    orchestration: "Orchestration",
    cloud_computing: "Cloud Computing",
    linux: "Linux",
    networking: "Networking",
    site_reliability: "Site Reliability (SRE)",
    monitoring_observability: "Monitoring & Observability",
    infrastructure_as_code: "Infrastructure as Code (IaC)",

    cybersecurity: "Cybersecurity",
    app_security: "Application Security",
    network_security: "Network Security",
    iam_security: "IAM (Identity & Access Management)",
    vulnerability_management: "Vulnerability Management",
    penetration_testing: "Penetration Testing",

    quality_assurance: "Quality Assurance (QA)",
    manual_testing: "Manual Testing",
    automation_testing: "Automation Testing",
    performance_testing: "Performance Testing",
    test_management: "Test Management",

    ui_ux_design: "UI/UX Design",
    product_design: "Product Design",
    graphic_design: "Graphic Design",
    branding: "Branding",
    illustration: "Illustration",
    video_editing: "Video Editing",
    motion_graphics: "Motion Graphics",
    photography: "Photography",
    copywriting: "Copywriting",
    content_writing: "Content Writing",
    content_strategy: "Content Strategy",

    product_management: "Product Management",
    project_management: "Project Management",
    program_management: "Program Management",
    agile_scrum: "Agile/Scrum",
    business_analysis: "Business Analysis",
    process_improvement: "Process Improvement",
    operations: "Operations",
    strategy_planning: "Strategy Planning",
    okr_kpi: "OKR/KPI",

    digital_marketing: "Digital Marketing",
    social_media: "Social Media",
    seo: "SEO",
    sem_ppc: "SEM/PPC",
    email_marketing: "Email Marketing",
    performance_marketing: "Performance Marketing",
    brand_marketing: "Brand Marketing",
    market_research: "Market Research",
    pr_communications: "PR & Communications",
    community_management: "Community Management",

    finance: "Finance",
    accounting: "Accounting",
    bookkeeping: "Bookkeeping",
    taxation: "Taxation",
    budgeting_forecasting: "Budgeting & Forecasting",
    financial_analysis: "Financial Analysis",
    audit_compliance: "Audit & Compliance",

    human_resources: "Human Resources",
    recruitment: "Recruitment",
    people_operations: "People Operations",
    payroll: "Payroll",
    learning_development: "Learning & Development",

    legal: "Legal",
    contract_management: "Contract Management",
    compliance: "Compliance",
    risk_management: "Risk Management",

    procurement: "Procurement",
    inventory_management: "Inventory Management",
    supply_chain: "Supply Chain",
    logistics: "Logistics",
    warehouse_management: "Warehouse Management",
    shipping_fulfillment: "Shipping & Fulfillment",

    healthcare: "Healthcare",
    education: "Education",
    hospitality: "Hospitality",
    retail: "Retail",
    manufacturing: "Manufacturing",
    construction: "Construction",
  },
} as const satisfies Record<LabelLanguage, Record<SkillCategory, string>>;
